### PR TITLE
bt download_submissions

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
@mpsijm

### CODE REVIEW

**Review by mpsijm — APPROVED** [review]

**Comment by RagnarGrootKoerkamp** [comment]
Thanks for fixing and merging :heart_eyes:

**Comment by RagnarGrootKoerkamp** [comment]
While we're at it, we should probably also download the scoreboard, just so we have it.

Also, cool how small the diff is to make the parallel download :)

**Comment by mpsijm** [comment]
Adding the scoreboard to the download sounds good! I already shut down, but feel free to add it 🙂

**Comment by mpsijm** [comment]
See https://github.com/mpsijm/BAPCtools/commit/cc15a1200706d8af2f4811d20501848b503d2574, but it doesn't completely work yet. Besides the scoreboard's JSON data (i.e. the stuff we download in `bin/misc/download_scoreboard.sh`), I wanted to also download the static scoreboard zip and clarifications html, but that doesn't work yet, so I've opened https://github.com/DOMjudge/domjudge/issues/2768 for that :stuck_out_tongue:

**Pull request merged**
