### PR TITLE
substitute {count}

### PR DESCRIPTION
**Pull request by mzuenni**
#378

### CODE REVIEW

**Comment by mzuenni** [comment]
@thorehusfeldt it seems like the regex is wrong here? A generator is allowed to have `{name}` (and now) `{count}` any number of times?

**Review by RagnarGrootKoerkamp — APPROVED** [review]

**Comment by mzuenni** [comment]
can someone proofread my regex? ^^'
And changes to the schemas have to be submitted somewhere else too, right?

**Comment by thorehusfeldt** [comment]
The regex seems to do what we want it to. (I’ve tested a bunch of them now…) You can always write more no-instances in https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/test/generator_yaml/bad_generators.yaml ; the CUE schema should then reject them automagically.

The JSON schema indeed has to be submitted to schemastore.org, and that takes typically a few days. (I’ve done this so far.)

**Comment by mzuenni** [comment]
Can you submit this update again? :)

**Pull request merged**
