### PR TITLE
Update Python version (3.10)

### PR DESCRIPTION
**Pull request by Nonoze**

### CODE REVIEW

**Comment by RagnarGrootKoerkamp** [comment]
Hey! What was the issue exactly?
I think @mpsijm has some unpushed changes somewhere to actually make things compatible again with 3.6.

**Comment by mpsijm** [comment]
Ehhh no, the other way around unfortunately; I also updated the readme to require 3.10 😅 https://github.com/RagnarGrootKoerkamp/BAPCtools/commit/b21db3256ad08862f79652623c72f004631f81e5

Indeed, my branch for #102 is not ready for merging yet, but feel free to cherry-pick the linked commit already 🙂

**Comment by Nonoze** [comment]
Hi, I tried to run it with python 3.8, and there were some errors (line 81
in verdicts.py) because of the function “match/case” I think, I don’t know
if you understand what I mean.

I deleted my pool request because I saw that someone has mentioned it on
the issue part.

Bye and thanks for this great tool !

**Comment by Nonoze** [comment]
Oh ok, no problem it works know (I will still check that this evening)

**Comment by mpsijm** [comment]
Ah, I see now that I made the same comment in https://github.com/RagnarGrootKoerkamp/BAPCtools/issues/388#issuecomment-2310933537 😂 

Hopefully upgrading to Python 3.10 isn't a problem for you! If it is, we can downgrade the match/case to plain if/else to make it compatible with older version of Python again 🙂 No guarantee that it will happen soon though, since we have some contests coming up 😇 But feel free to make a PR 😄

**Comment by Nonoze** [comment]
Haha no worries it’s ok for me (I just had to reinstall my Ubuntu wsl
because of that but it’s done now and I should have done it soon so it’s
not a problem).

Good preparation of the bapc I suppose

**Pull request closed without merging**
